# Generated by Django 6.0 on 2026-01-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('max_students', models.PositiveIntegerField(default=0, help_text="Maksimal o'quvchilar soni")),
                ('max_teachers', models.PositiveIntegerField(default=0, help_text="Maksimal o'qituvchilar soni")),
                ('max_groups', models.PositiveIntegerField(default=0, help_text='Maksimal guruhlar soni')),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_live_games', models.BooleanField(default=False)),
                ('has_custom_branding', models.BooleanField(default=False)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, help_text="Oylik narx (so'mda)", max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0.0, help_text="Yillik narx (so'mda)", max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Plan tavsifi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan Limit',
                'verbose_name_plural': 'Plan Limitlari',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Oylik'), ('yearly', 'Yillik')], default='monthly', max_length=10)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Subscription boshlangan vaqt', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Subscription tugash vaqti', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Subscription hozir aktivmi')),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Trial muddati tugash vaqti', null=True)),
                ('payment_gateway', models.CharField(blank=True, help_text="To'lov gateway nomi (payme, click, stripe, manual)", max_length=50)),
                ('gateway_subscription_id', models.CharField(blank=True, help_text='Gateway ichidagi subscription ID', max_length=100)),
                ('auto_renew', models.BooleanField(default=True, help_text='Avtomatik yangilanish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='centers.center')),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obunalar',
                'indexes': [models.Index(fields=['center', 'is_active'], name='billing_sub_center__526307_idx'), models.Index(fields=['expires_at'], name='billing_sub_expires_b7e94d_idx')],
            },
        ),
    ]
