# Generated by Django 6.0 on 2025-12-28 10:13

import django.db.models.deletion
import groups.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('subject', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('invite_code', models.CharField(default=groups.models.generate_invite_code, editable=False, max_length=6, unique=True, verbose_name='Taklif kodi')),
                ('max_students', models.PositiveIntegerField(default=30, verbose_name='Maksimal o‘quvchilar soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arxivlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='centers.center')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ('-created_at',),
                'unique_together': {('center', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol a’zolik')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guruh o‘quvchisi',
                'verbose_name_plural': 'Guruh o‘quvchilari',
                'unique_together': {('group', 'student')},
            },
        ),
    ]
