# Generated by Django 6.0 on 2026-01-05 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-joined_at']},
        ),
        migrations.RemoveField(
            model_name='center',
            name='config',
        ),
        migrations.RemoveField(
            model_name='center',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='center',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='center',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_active',
        ),
        migrations.AddField(
            model_name='center',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='center',
            name='max_students',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='center',
            name='max_teachers',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='center',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='center',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Faol'), ('INACTIVE', 'Nofaol'), ('SUSPENDED', 'To‘xtatilgan')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='center',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=50),
        ),
        migrations.AddField(
            model_name='center',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='center',
            name='website',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Faol'), ('INACTIVE', 'Nofaol'), ('PENDING', 'Kutilmoqda')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('CENTER_ADMIN', 'Center Admin')], default='STUDENT', max_length=20),
        ),
        migrations.AlterModelTable(
            name='center',
            table='centers',
        ),
        migrations.AlterModelTable(
            name='membership',
            table='memberships',
        ),
    ]
