# Generated by Django 6.0 on 2026-01-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_options_alter_membership_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
